In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [51]:
df=pd.read_csv('Walmart Data Analysis and Forcasting.csv')

In [52]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,"$16,43,690.90",0,42.31,$2.57,211.096358,8.106
1,1,12-02-2010,"$16,41,957.44",1,38.51,$2.55,211.242170,8.106
2,1,19-02-2010,"$16,11,968.17",0,39.93,$2.51,211.289143,8.106
3,1,26-02-2010,"$14,09,727.59",0,46.63,$2.56,211.319643,8.106
4,1,05-03-2010,"$15,54,806.68",0,46.50,$2.63,211.350143,8.106

In [53]:
df.tail()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
6430,45,28-09-2012,"$7,13,173.95",0,64.88,$4.00,192.013558,8.684
6431,45,05-10-2012,"$7,33,455.07",0,64.89,$3.99,192.170412,8.667
6432,45,12-10-2012,"$7,34,464.36",0,54.47,$4.00,192.327265,8.667
6433,45,19-10-2012,"$7,18,125.53",0,56.47,$3.97,192.330854,8.667
6434,45,26-10-2012,"$7,60,281.43",0,58.85,$3.88,192.308899,8.667

In [54]:
df.shape

(6435, 8)

In [55]:
df.columns

Index(['Store', 'Date', ' Weekly_Sales ', 'Holiday_Flag', 'Temperature',
       ' Fuel_Price ', 'CPI', 'Unemployment'],
      dtype='str')

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Store           6435 non-null   int64
 1   Date            6435 non-null   str
 2    Weekly_Sales   6435 non-null   str
 3   Holiday_Flag    6435 non-null   int64
 4   Temperature     6435 non-null   float64
 5    Fuel_Price     6435 non-null   str
 6   CPI             6435 non-null   float64
 7   Unemployment    6435 non-null   float64
dtypes: float64(3), int64(2), str(3)
memory usage: 402.3 KB

In [57]:
df.isnull().sum()

Store             0
Date              0
 Weekly_Sales     0
Holiday_Flag      0
Temperature       0
 Fuel_Price       0
CPI               0
Unemployment      0
dtype: int64

In [58]:
df.ffill(inplace=True)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,"$16,43,690.90",0,42.31,$2.57,211.096358,8.106
1,1,12-02-2010,"$16,41,957.44",1,38.51,$2.55,211.242170,8.106
2,1,19-02-2010,"$16,11,968.17",0,39.93,$2.51,211.289143,8.106
3,1,26-02-2010,"$14,09,727.59",0,46.63,$2.56,211.319643,8.106
4,1,05-03-2010,"$15,54,806.68",0,46.50,$2.63,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,"$7,13,173.95",0,64.88,$4.00,192.013558,8.684
6431,45,05-10-2012,"$7,33,455.07",0,64.89,$3.99,192.170412,8.667
6432,45,12-10-2012,"$7,34,464.36",0,54.47,$4.00,192.327265,8.667
6433,45,19-10-2012,"$7,18,125.53",0,56.47,$3.97,192.330854,8.667
6434,45,26-10-2012,"$7,60,281.43",0,58.85,$3.88,192.308899,8.667

In [59]:
df.duplicated().sum()

np.int64(0)

In [60]:
df.drop_duplicates(inplace=True)

In [61]:
df.describe()

             Store  Holiday_Flag  Temperature          CPI  Unemployment
count  6435.000000   6435.000000  6435.000000  6435.000000   6435.000000
mean     23.000000      0.069930    60.663782   171.578394      7.999151
std      12.988182      0.255049    18.444933    39.356712      1.875885
min       1.000000      0.000000    -2.060000   126.064000      3.879000
25%      12.000000      0.000000    47.460000   131.735000      6.891000
50%      23.000000      0.000000    62.670000   182.616521      7.874000
75%      34.000000      0.000000    74.940000   212.743293      8.622000
max      45.000000      1.000000   100.140000   227.232807     14.313000